### ISSUE TITLE
podpięcie info o nie byciu klientem pod główny template html + link do "rejestruj"

### ISSUE THREAD

**Issue by ksazon** [ksazon/ussr#109]
![image](https://user-images.githubusercontent.com/14951624/34653653-4a3daa10-f3ef-11e7-9043-7bf8ce2ee3dc.png)

**Comment by marenty** [comment]
Tu nie chodzi o bycie niezarejestrowanym, tylko o to, że wystąpił jakiś błąd. Każdy nowy użytkownik jest z automatu przypisywany klientowi. Ta strona pojawia się tylko w momencie, gdy ktoś namiesza w bazie, lub jest pracownikiem. Wg. mnie jeśli pracownik chce złożyć zamówienie, może założyć drugie konto lub poprosić admina o przypisanie klienta
